New1/urls.py
from django.urls import path
from .views import (PostList, PostDetail, PostCreate, PostUpdate, PostDelete, ResponseCreate, Responses,
                    response_accept, response_delete, )

urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDelete.as_view(), name='post_delete'),
    path('<int:pk>/response/create/', ResponseCreate.as_view(), name='response_create'),
    path('responses/', Responses.as_view(), name='responses'),
    path('response/accept/<int:pk>', response_accept, name='response_accept'),
    path('response/delete/<int:pk>', response_delete, name='response_delete'),
]

News/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('posts/', include('New1.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include('allauth.urls')),
    path('logout/', LogoutView.as_view()),
    path('post/', include('New1.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

New1/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models import TextField
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    CATEGORIES = (
        ('healers', 'Хилы'),
        ('tanks', 'Танки'),
        ('dd', 'ДД'),
        ('dealers', 'Торговцы'),
        ('gildmasters', 'Гилдмастеры'),
        ('questgivers', 'Квестгиверы'),
        ('blacksmiths', 'Кузнецы'),
        ('tanners', 'Кожевники'),
        ('potionsmakers', 'Зельевары'),
        ('spell_masters', 'Мастера заклинаний')
    )
    category = models.CharField(max_length=25, choices=CATEGORIES, verbose_name='Категория', default='healers')
    dateCreation = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=128, verbose_name='Названиe', default='Здесь должен быть заголовок...')
    content = RichTextUploadingField(verbose_name='Текст объявления', default='Здесь должен быть текст...')

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

class Response(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = TextField(verbose_name='Отклик', default='')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    dateCreation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.id} Отзыв {self.text} от {self.author}'

    def get_absolute_url(self):
        return reverse(viewname='post_detail', kwargs={'pk':self.post_id})

templates/post.html
<!DOCTYPE html>

{% extends 'flatpages/default.html' %}


{% block title %}
Объявление
{% endblock title %}

{% block content %}
    {% autoescape off %}
        <h2>Объявление "{{ post.title }}" от {{post.author}} </h2>
        <h5>{{ post.content }}</h5>
    {% endautoescape %}

<form action="{% url 'response_create' post.id %}" method="post" enctype="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Сохранить" />
</form>

{%if post.response_set.all%}
<h5>Все отклики</h5>
{% for response in post.response_set.all %}
<table>
    <td>{{response.author.username}}</td>
    <td>{{response.text}}</td>

</table>

{%endfor%}
{%endif%}

<a href="/posts/">
    <button>На главную</button>
</a>
{% endblock content %}

templates/post_create.html
<!DOCTYPE html>

<!DOCTYPE html>

{% extends 'flatpages/default.html' %}


{% block content %}


<h1>Добавить объявление</h1>
<hr>
<form action="" method="post" enctype="">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>

<input type="button" value="Назад" onclick="javascript:history.go(-1)">
{% endblock content %}

templates/post_delete.html
{% block content %}
<h1>{{ page_title }}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем запись с заголовком "{{ object.title }}"?</p>
    <input type="submit" value="Delete" class="btn btn-danger"/>
    <a class="btn btn-secondary" role="button" href="{{ previous_page_url }}">Cancel</a>
</form>
{% endblock content %}

templates/post_edit.html
<!DOCTYPE html>

{% block content %}
<h1>Редактировать объявление</h1>
<hr>
<form action="" method="post" enctype="">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>

<input type="button" value="Назад" onclick="javascript:history.go(-1)">
{% endblock content %}

templates/posts.html
<!DOCTYPE html>

{% extends 'flatpages/default.html' %}


{% block title %}
{% endblock title%}

{% block content %}
{% if perms.New1.change_post %}

    <h2>Все объявления</h2>

    <a href="{%url 'post_create'%}">
        <button>Добавить объявление</button>
    </a>
    <a href="{%url 'responses'%}">
        <button>Перейти в чат</button>
    </a>
    {%endif%}

    <table>
        {% for post in posts %}
            <tr>
                {% autoescape off %}
                <td>
                    <a href="/posts/{{ post.id }}" style="font-size: 14px;"><b>{{ post.title }}</b></a> <p>{{post.content}}</p>
                </td>
                {% endautoescape %}
                <td>{{ post.author }}</td>
                <td>{{ post.category }}</td>
                <td>
                    {% if perms.New1.change_post %}
                    <a href="{% url 'post_update' pk=post.id %}">Изменить / </a>
                    {% endif %}
                    {% if perms.New1.delete_post %}
                    <a href="{% url 'post_delete' pk=post.id %}">Удалить</a>
                    {% endif %}
                </td>
            </tr>

        {% endfor %}
    </table>
    {% endblock content %}

templates/response_create.html
<!DOCTYPE html>

{% block content %}
<h1>Отклик</h1>
<hr>
<form action="" method="post" enctype="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>

<input type="button" value="Назад" onclick="javascript:history.go(-1)">
{% endblock content %}

templates/responses.html
{% block title %}
Все отклики на объявления пользователя {{user.username}}
{% endblock title%}

{% block content %}

<form action="", method="get">
    {{filterset.form.as_p}}
    <input type="submit", value="Найти">
</form>
 <a href="/posts/">
    <button>Вернуться на главную</button>
    </a>
<hr>
<h5>Все отклики на выбранное объявление:</h5>
{% if filterset.qs %}
{% for response in filterset.qs %}
<h5>Отклик от пользователя {{ response.author }}: {{ response.text }}</h5>
    {% if response.status == False %}
    <a href="{% url 'response_accept' pk=response.id %}">Принять / </a>
    <a href="{% url 'response_delete' pk=response.id %}">Удалить </a>
    {% else %}
    <b style="color:green">Отклик принят</b>
    {%endif%}
{%endfor%}
{%else%}
<h5>No resp</h5>
{% endif %}

{% endblock content %}

templates/subscriptions.html
{% block title %}
Посмотреть мои подписки
{% endblock title %}

{% block content %}
    {% for post in posts %}
        <p>
            {{post.id}}.
            {{ post.title }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{ post.id }}" />

                {% if post.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}